// RTSky - precompiled shader bytecode
// The headers are generated by DXC (-Fh / -Vn) into the build directory.
#include "ShaderBlobs.h"

#include "RTSkyShader_Transmittance.h"
#include "RTSkyShader_MultiScatter.h"
#include "RTSkyShader_SkyView.h"
#include "RTSkyShader_SkyProject.h"
#include "RTSkyShader_Prepare.h"
#include "RTSkyShader_TraceInline.h"
#include "RTSkyShader_TraceLibrary.h"
#include "RTSkyShader_Temporal.h"
#include "RTSkyShader_ATrous.h"
#include "RTSkyShader_Composite.h"
#include "RTSkyShader_Probe.h"
#include "RTSkyShader_DebugBlit.h"

namespace rtsky::render {

ShaderBlob GetShader(ShaderId id)
{
    switch (id)
    {
    case ShaderId::Transmittance: return { g_Transmittance, sizeof(g_Transmittance) };
    case ShaderId::MultiScatter: return { g_MultiScatter, sizeof(g_MultiScatter) };
    case ShaderId::SkyView: return { g_SkyView, sizeof(g_SkyView) };
    case ShaderId::SkyProject: return { g_SkyProject, sizeof(g_SkyProject) };
    case ShaderId::Prepare: return { g_Prepare, sizeof(g_Prepare) };
    case ShaderId::TraceInline: return { g_TraceInline, sizeof(g_TraceInline) };
    case ShaderId::TraceLibrary: return { g_TraceLibrary, sizeof(g_TraceLibrary) };
    case ShaderId::Temporal: return { g_Temporal, sizeof(g_Temporal) };
    case ShaderId::ATrous: return { g_ATrous, sizeof(g_ATrous) };
    case ShaderId::Composite: return { g_Composite, sizeof(g_Composite) };
    case ShaderId::Probe: return { g_Probe, sizeof(g_Probe) };
    case ShaderId::DebugBlit: return { g_DebugBlit, sizeof(g_DebugBlit) };
    default: return {};
    }
}

} // namespace rtsky::render
